site_name: Mailjet Bundle
site_description: Symfony bundle for handling Mailjet API V3.
site_author: Titouan BENOIT
copyright: MIT
repo_url: https://github.com/mailjet/mailjetBundle
edit_uri: edit/master/src/Resources/doc/
docs_dir: 'src/Resources/doc'
site_dir: "docs"
pages:
    - Home: index.md
    - Setup: setup.md
    - Configuration: configuration.md
    - SwiftMailer: swiftmailer.md
    - Contact Provider: contact-provider.md
    - Usage: usage.md
    - Event API (webhook): event-api.md
    - Symfony Debug Toolbar: symfony-debug-toolbar.md
    - Tests: tests.md
    - Build Documentation: build-documentation.md
    - Mailjet Doc: mailjet-doc.md
    - Contributing: CONTRIBUTING.md
theme: readthedocs
markdown_extensions:
    - pymdownx.github
